#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2015 Robert Welin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

USAGE='<base-revision> <branch-base-name>'

. git-sh-setup
require_work_tree_exists

if [ $# -lt 2 ]
then
    exit 1
fi

base="$1"
branch_base_name="$2"

if ! git merge-base --is-ancestor "$base" HEAD
then
    echo "Current HEAD is not child of base revision $base"
    exit 1
fi

base_revision=$(git rev-parse "$base")
num_commits=$(git log --oneline "$base_revision"..HEAD | wc -l)
branch_head="$branch_base_name-$num_commits"

while [ ! "$(git rev-parse HEAD)" = "$base_revision" ]
do
    if [ "$num_commits" -lt 1 ]
    then
        echo "Assert: num_commits is less than one"
        exit 1
    fi

    branch="$branch_base_name-$num_commits"
    num_commits=$((num_commits-1))

    git checkout -b "$branch"
    git checkout HEAD~1
done

git checkout "$branch_head"
